### ISSUE TITLE
The link of English version is unavailable

### ISSUE THREAD

**Issue by licj1** [antonindurieux/data_challenge-unsupervised_anomaly_detection#1]
Hello,

Thanks for your excellent work, but I find that the link to the English version is unavailable, could you please provide it again?

Look forward to your reply, thanks!

**Comment by antonindurieux** [comment]
Hello,

Thanks for your interest. Unfortunately I don't have much time to maintain the small website on which I made the english version available so I preferred to took it offline.

That being said, you can still find the source markdown file of the english version [here](https://github.com/antonindurieux/personal-website-offline-/blob/main/_portfolio/2_accelerometer_anomaly_detection.md), I think the format is still pretty readable and might be enough for your needs ?

**Comment by licj1** [comment]
> Hello,
> 
> Thanks for your interest. Unfortunately I don't have much time to maintain the small website on which I made the english version available so I preferred to took it offline.
> 
> That being said, you can still find the source markdown file of the english version [here](https://github.com/antonindurieux/personal-website-offline-/blob/main/_portfolio/2_accelerometer_anomaly_detection.md), I think the format is still pretty readable and might be enough for your needs ?

Hello,
Thanks a lot for the prompt reply. The source markdown is enough for learning. Thank you!
